artifact_uri: /Users/mdancho/Desktop/learning_labs/lab_40_docker/mflow_test_2/1/9d80021e309b493da8ab7064f7eb15cd/artifacts
end_time: 1596576312712
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 9d80021e309b493da8ab7064f7eb15cd
run_uuid: 9d80021e309b493da8ab7064f7eb15cd
source_name: ''
source_type: 4
source_version: ''
start_time: 1596576306095
status: 3
tags: []
user_id: mdancho
