artifact_uri: /Users/mdancho/Desktop/learning_labs/lab_40_docker/mflow_test_2/1/46c690ca7fa6440bbf4fa8dc003746f4/artifacts
end_time: 1596576321008
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 46c690ca7fa6440bbf4fa8dc003746f4
run_uuid: 46c690ca7fa6440bbf4fa8dc003746f4
source_name: ''
source_type: 4
source_version: ''
start_time: 1596576312759
status: 3
tags: []
user_id: mdancho
