artifact_uri: /Users/mdancho/Desktop/learning_labs/lab_40_docker/mflow_test_2/1/0b3a50b51c8c47c6956f1f84b9c52e51/artifacts
end_time: 1596576330384
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 0b3a50b51c8c47c6956f1f84b9c52e51
run_uuid: 0b3a50b51c8c47c6956f1f84b9c52e51
source_name: ''
source_type: 4
source_version: ''
start_time: 1596576321054
status: 3
tags: []
user_id: mdancho
