artifact_uri: /Users/mdancho/Desktop/learning_labs/lab_40_docker/mflow_test_2/1/34b40fa9f61448f1abf833bccb5a00ce/artifacts
end_time: 1596576345722
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 34b40fa9f61448f1abf833bccb5a00ce
run_uuid: 34b40fa9f61448f1abf833bccb5a00ce
source_name: ''
source_type: 4
source_version: ''
start_time: 1596576330432
status: 3
tags: []
user_id: mdancho
