artifact_uri: /Users/mdancho/Desktop/learning_labs/lab_40_docker/mflow_test_2/1/5cc3576a6c8347eda8e2e5a157338180/artifacts
end_time: 1596576306049
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 5cc3576a6c8347eda8e2e5a157338180
run_uuid: 5cc3576a6c8347eda8e2e5a157338180
source_name: ''
source_type: 4
source_version: ''
start_time: 1596576300525
status: 3
tags: []
user_id: mdancho
