artifact_uri: /Users/mdancho/Desktop/learning_labs/lab_40_docker/mflow_test_2/1/409c2b19b03f41e6961b813533c598bd/artifacts
end_time: 1596576365078
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 409c2b19b03f41e6961b813533c598bd
run_uuid: 409c2b19b03f41e6961b813533c598bd
source_name: ''
source_type: 4
source_version: ''
start_time: 1596576345769
status: 3
tags: []
user_id: mdancho
